-- 1. Create the `bookings` table
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  client_phone text not null,
  client_email text,
  service_name text not null,
  service_price int,              -- Price in EUR
  service_duration text,          -- Display text (e.g. "1h 15")
  service_duration_min int,       -- Duration in minutes
  booking_date date not null,     -- Selected date
  booking_time text not null,     -- Selected time (e.g. "10:30")
  status text default 'confirmed'
);

-- 2. Enable Row Level Security (RLS)
alter table public.bookings enable row level security;

-- 3. Create Policy: Allow ANYONE to INSERT (create booking)
create policy "Enable insert for everyone" 
on public.bookings for insert 
with check (true);

-- 4. Create Policy: Allow EVERYONE to READ bookings (needed to block slots)
-- Note: In a real app, maybe limit readable columns? But here we need to check availability.
create policy "Enable read access for all users" 
on public.bookings for select 
using (true);

-- 5. Create Policy: Allow DELETE only if you have the secret key?
-- Ideally, admin actions should be done via a secure backend or authenticated user.
-- For simple demo: allow delete if you are authenticated or just allow everyone if RLS is very loose.
-- Since current admin is client-side password only, we need loose delete policy for now, 
-- OR use a secret service key for admin. But we are client-side only.
-- Let's allow delete for now to mimic the localStorage behavior.
create policy "Enable delete for everyone" 
on public.bookings for delete 
using (true);
